import React, { useState, useMemo, useEffect } from 'react';
import { useHemo } from '../context/HemoContext';
import { WhatsAppDispatcher } from '../domain/WhatsAppDispatcher';
import { HeadNurseReportFormat } from '../types';
import {
  X,
  Send,
  Copy,
  FileText,
  CheckCircle2,
  AlertTriangle,
  ExternalLink,
  Globe,
  Phone,
  Layers,
  Zap,
  UserCheck,
  Edit3,
  RotateCcw,
  Check
} from 'lucide-react';

interface HeadNurseReportModalProps {
  onClose: () => void;
}

export const HeadNurseReportModal: React.FC<HeadNurseReportModalProps> = ({ onClose }) => {
  const { settings, updateSettings, dailyAssignments, machines, selectedDate, showToast } = useHemo();
  const [headNurseName, setHeadNurseName] = useState(settings.headNurseName || 'Kepala Ruang HD');
  const [headNursePhone, setHeadNursePhone] = useState(settings.headNursePhone || '');
  const [saveToSettings, setSaveToSettings] = useState(true);
  const [copied, setCopied] = useState(false);

  // Format Switch State
  const [formatMode, setFormatMode] = useState<HeadNurseReportFormat>('LENGKAP_MESIN');
  // Editable text state
  const [isCustomEditing, setIsCustomEditing] = useState(false);
  const [editedText, setEditedText] = useState<string>('');

  const isSample = WhatsAppDispatcher.isSamplePhoneNumber(headNursePhone);
  const isValid = WhatsAppDispatcher.isValidPhoneNumber(headNursePhone);
  const isMobile = WhatsAppDispatcher.isMobileDevice();

  // Generate standard report based on active formatMode
  const autoGeneratedText = useMemo(() => {
    return WhatsAppDispatcher.generateHeadNurseDailyAllocationMessage(
      selectedDate,
      dailyAssignments,
      machines,
      settings.hospitalName,
      settings.roomName,
      headNurseName,
      formatMode
    );
  }, [selectedDate, dailyAssignments, machines, settings.hospitalName, settings.roomName, headNurseName, formatMode]);

  // When format mode changes and not editing, or when initialized
  useEffect(() => {
    if (!isCustomEditing) {
      setEditedText(autoGeneratedText);
    }
  }, [autoGeneratedText, isCustomEditing]);

  const finalReportText = isCustomEditing ? editedText : autoGeneratedText;

  const handleSelectFormat = (mode: HeadNurseReportFormat) => {
    setFormatMode(mode);
    const newText = WhatsAppDispatcher.generateHeadNurseDailyAllocationMessage(
      selectedDate,
      dailyAssignments,
      machines,
      settings.hospitalName,
      settings.roomName,
      headNurseName,
      mode
    );
    setEditedText(newText);
    setIsCustomEditing(false);
  };

  const handleToggleEdit = () => {
    if (!isCustomEditing) {
      setEditedText(finalReportText);
      setIsCustomEditing(true);
      showToast('Mode edit aktif. Anda dapat mengubah isi pesan langsung.', 'info');
    } else {
      setIsCustomEditing(false);
      showToast('Perubahan teks tersimpan untuk dikirim.', 'success');
    }
  };

  const handleResetToAuto = () => {
    setEditedText(autoGeneratedText);
    setIsCustomEditing(false);
    showToast('Teks dikembalikan ke format otomatis.', 'info');
  };

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(finalReportText);
      setCopied(true);
      showToast('Laporan harian berhasil disalin ke clipboard!', 'success');
      setTimeout(() => setCopied(false), 2500);
    } catch {
      showToast('Gagal menyalin laporan.', 'error');
    }
  };

  const persistSettingsIfRequested = () => {
    if (saveToSettings && (headNurseName !== settings.headNurseName || headNursePhone !== settings.headNursePhone)) {
      updateSettings({
        ...settings,
        headNurseName: headNurseName.trim(),
        headNursePhone: headNursePhone.trim(),
      });
    }
  };

  const handleSendWA = () => {
    if (!headNursePhone.trim()) {
      showToast('Masukkan nomor WhatsApp Kepala Ruangan terlebih dahulu, atau gunakan opsi "Pilih Kontak di WA".', 'info');
      return;
    }

    if (isSample) {
      const confirmSend = window.confirm(
        `Nomor "${headNursePhone}" terdeteksi sebagai nomor contoh bawaan sistem (081234567801).\n\nApakah Anda ingin tetap membuka WhatsApp dengan nomor ini, atau ingin menggantinya dulu dengan nomor asli Karu?`
      );
      if (!confirmSend) return;
    }

    persistSettingsIfRequested();
    WhatsAppDispatcher.openWhatsApp(headNursePhone.trim(), finalReportText);
    showToast(`Membuka WhatsApp untuk ${headNurseName}... Teks laporan disalin!`, 'success');
    onClose();
  };

  const handleSendGeneralWA = () => {
    persistSettingsIfRequested();
    WhatsAppDispatcher.openWhatsApp(null, finalReportText);
    showToast(`Membuka WhatsApp... Silakan pilih kontak ${headNurseName}!`, 'success');
    onClose();
  };

  const handleSendDesktopWeb = () => {
    persistSettingsIfRequested();
    WhatsAppDispatcher.openWhatsApp(headNursePhone.trim() || null, finalReportText, true);
    showToast('Membuka WhatsApp Web di browser baru...', 'success');
    onClose();
  };

  const manualUrl = WhatsAppDispatcher.getWhatsAppUrl(headNursePhone, finalReportText);

  // Format label name helper
  const getFormatLabel = () => {
    switch (formatMode) {
      case 'LENGKAP_MESIN':
        return 'Format Lengkap (Urut Mesin)';
      case 'RINGKAS':
        return 'Format Ringkas (Cepat)';
      case 'NAMA_PERAWAT':
        return 'Format Berdasarkan Nama (A-Z)';
      default:
        return 'Laporan HD';
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-4 bg-slate-900/60 backdrop-blur-xs overflow-y-auto animate-in fade-in duration-200">
      <div className="bg-white dark:bg-slate-900 rounded-3xl max-w-2xl w-full p-5 sm:p-6 shadow-2xl border border-slate-200/80 dark:border-slate-800 my-8 space-y-4 max-h-[92vh] flex flex-col animate-in zoom-in-95 duration-200">
        {/* Header */}
        <div className="flex items-center justify-between pb-3.5 border-b border-slate-100 dark:border-slate-800 shrink-0">
          <div className="flex items-center gap-2.5">
            <div className="w-10 h-10 rounded-2xl bg-blue-100 dark:bg-blue-950 text-blue-700 dark:text-blue-300 flex items-center justify-center shadow-xs border border-blue-200 dark:border-blue-800">
              <FileText className="w-5 h-5" />
            </div>
            <div>
              <div className="flex items-center gap-2 flex-wrap">
                <h3 className="text-base font-extrabold text-slate-900 dark:text-white">Laporan Harian ke Karu</h3>
                <span className="text-[10px] font-bold px-2 py-0.5 rounded-full bg-blue-100 text-blue-800 dark:bg-blue-950 dark:text-blue-300 border border-blue-200 dark:border-blue-800">
                  {getFormatLabel()}
                </span>
                {isCustomEditing && (
                  <span className="text-[10px] font-extrabold px-2 py-0.5 rounded-full bg-amber-100 text-amber-800 dark:bg-amber-950 dark:text-amber-300 border border-amber-300">
                    Diedit Manual
                  </span>
                )}
              </div>
              <p className="text-xs text-slate-500 dark:text-slate-400 font-medium">{WhatsAppDispatcher.formatIndonesianDate(selectedDate)}</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="text-slate-400 hover:text-slate-600 dark:hover:text-slate-200 p-2 rounded-xl hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        <div className="space-y-4 overflow-y-auto pr-1 flex-1 text-xs">
          {/* Karu Identity Inputs */}
          <div className="bg-slate-50 dark:bg-slate-800/60 p-3.5 rounded-2xl border border-slate-200/80 dark:border-slate-700/80 space-y-3">
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              <div>
                <label className="block text-xs font-bold text-slate-700 dark:text-slate-300 mb-1">
                  Nama Kepala Ruang
                </label>
                <input
                  type="text"
                  value={headNurseName}
                  onChange={(e) => setHeadNurseName(e.target.value)}
                  placeholder="Contoh: Ns. Hendra Wijaya, S.Kep"
                  className="w-full px-3 py-2 text-xs rounded-xl border border-slate-300 dark:border-slate-600 bg-white dark:bg-slate-900 text-slate-900 dark:text-white font-medium focus:ring-2 focus:ring-blue-500 focus:outline-hidden"
                />
              </div>
              <div>
                <div className="flex items-center justify-between mb-1">
                  <label className="text-xs font-bold text-slate-700 dark:text-slate-300 flex items-center gap-1">
                    <Phone className="w-3 h-3 text-emerald-600" />
                    No. WhatsApp Karu
                  </label>
                  {isSample && (
                    <span className="text-[10px] font-extrabold px-1.5 py-0.2 rounded bg-amber-100 text-amber-800 dark:bg-amber-950 dark:text-amber-300 border border-amber-300 flex items-center gap-0.5">
                      <AlertTriangle className="w-2.5 h-2.5" />
                      Nomor Contoh
                    </span>
                  )}
                </div>
                <input
                  type="tel"
                  value={headNursePhone}
                  onChange={(e) => setHeadNursePhone(e.target.value)}
                  placeholder="Contoh: 08123456789"
                  className="w-full px-3 py-2 text-xs rounded-xl border border-slate-300 dark:border-slate-600 bg-white dark:bg-slate-900 text-slate-900 dark:text-white font-mono font-bold focus:ring-2 focus:ring-blue-500 focus:outline-hidden"
                />
              </div>
            </div>

            {isSample && (
              <p className="text-[11px] text-amber-700 dark:text-amber-300 bg-amber-50/80 dark:bg-amber-950/40 p-2.5 rounded-xl border border-amber-200 dark:border-amber-800/60">
                Nomor di atas adalah nomor contoh bawaan sistem. Silakan ganti dengan nomor WhatsApp aktif Karu Anda agar chat langsung terbuka ke kontaknya.
              </p>
            )}

            <label className="flex items-center gap-2 cursor-pointer text-slate-600 dark:text-slate-300">
              <input
                type="checkbox"
                checked={saveToSettings}
                onChange={(e) => setSaveToSettings(e.target.checked)}
                className="w-4 h-4 rounded text-blue-600 border-slate-300 focus:ring-blue-500"
              />
              <span className="text-[11px] font-medium">
                Simpan nomor & nama ini secara permanen ke Pengaturan Sistem
              </span>
            </label>
          </div>

          {/* Sakelar Format Laporan (Format Switcher) */}
          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <label className="text-xs font-bold text-slate-700 dark:text-slate-300 flex items-center gap-1.5">
                <span>Pilih Format Laporan:</span>
              </label>
              <div className="flex items-center gap-2">
                {isCustomEditing && (
                  <button
                    type="button"
                    onClick={handleResetToAuto}
                    className="text-[11px] font-semibold text-rose-600 dark:text-rose-400 hover:underline flex items-center gap-1"
                    title="Kembalikan teks sesuai template otomatis"
                  >
                    <RotateCcw className="w-3 h-3" />
                    <span>Reset Otomatis</span>
                  </button>
                )}
                <button
                  type="button"
                  onClick={handleToggleEdit}
                  className={`text-[11px] font-bold px-2 py-1 rounded-lg border transition-all flex items-center gap-1 ${
                    isCustomEditing
                      ? 'bg-amber-50 text-amber-700 border-amber-300 dark:bg-amber-950 dark:text-amber-300 dark:border-amber-800'
                      : 'bg-slate-100 text-slate-700 border-slate-300 dark:bg-slate-800 dark:text-slate-300 dark:border-slate-700 hover:bg-slate-200'
                  }`}
                  title={isCustomEditing ? 'Selesai menyunting teks' : 'Edit teks langsung sebelum dikirim'}
                >
                  {isCustomEditing ? <Check className="w-3.5 h-3.5" /> : <Edit3 className="w-3.5 h-3.5" />}
                  <span>{isCustomEditing ? 'Selesai Edit' : 'Edit Teks Langsung'}</span>
                </button>
              </div>
            </div>

            {/* Segmented Control 3 Buttons */}
            <div className="grid grid-cols-3 gap-1.5 p-1 bg-slate-100 dark:bg-slate-800/80 rounded-2xl border border-slate-200 dark:border-slate-700">
              <button
                type="button"
                onClick={() => handleSelectFormat('LENGKAP_MESIN')}
                className={`py-2 px-2 rounded-xl text-[11px] font-bold transition-all flex flex-col sm:flex-row items-center justify-center gap-1 text-center ${
                  formatMode === 'LENGKAP_MESIN'
                    ? 'bg-white dark:bg-slate-900 text-blue-700 dark:text-blue-300 shadow-xs border border-blue-200 dark:border-blue-800'
                    : 'text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white'
                }`}
              >
                <Layers className="w-3.5 h-3.5 shrink-0 text-blue-600 dark:text-blue-400" />
                <span className="truncate">Format Lengkap (Urut Mesin)</span>
              </button>

              <button
                type="button"
                onClick={() => handleSelectFormat('RINGKAS')}
                className={`py-2 px-2 rounded-xl text-[11px] font-bold transition-all flex flex-col sm:flex-row items-center justify-center gap-1 text-center ${
                  formatMode === 'RINGKAS'
                    ? 'bg-white dark:bg-slate-900 text-emerald-700 dark:text-emerald-300 shadow-xs border border-emerald-200 dark:border-emerald-800'
                    : 'text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white'
                }`}
              >
                <Zap className="w-3.5 h-3.5 shrink-0 text-emerald-600 dark:text-emerald-400" />
                <span className="truncate">Format Ringkas (Cepat)</span>
              </button>

              <button
                type="button"
                onClick={() => handleSelectFormat('NAMA_PERAWAT')}
                className={`py-2 px-2 rounded-xl text-[11px] font-bold transition-all flex flex-col sm:flex-row items-center justify-center gap-1 text-center ${
                  formatMode === 'NAMA_PERAWAT'
                    ? 'bg-white dark:bg-slate-900 text-indigo-700 dark:text-indigo-300 shadow-xs border border-indigo-200 dark:border-indigo-800'
                    : 'text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white'
                }`}
              >
                <UserCheck className="w-3.5 h-3.5 shrink-0 text-indigo-600 dark:text-indigo-400" />
                <span className="truncate">Urut Nama (A-Z)</span>
              </button>
            </div>
            <p className="text-[10px] text-slate-500 dark:text-slate-400 px-1">
              {formatMode === 'LENGKAP_MESIN' &&
                '💡 Format lengkap merinci status mesin, PIC, perawat dinas diurutkan dari nomor mesin HD-01 ke atas.'}
              {formatMode === 'RINGKAS' &&
                '💡 Format ringkas 1-baris per perawat dengan rentang mesin & tugas khusus/PIC, lebih padat dan cepat dibaca di layar ponsel.'}
              {formatMode === 'NAMA_PERAWAT' &&
                '💡 Format alfabetis mengurutkan nama perawat (A-Z) pada setiap sif untuk memudahkan pengecekan staf.'}
            </p>
          </div>

          {/* Preview Box / Editable Area */}
          <div className="space-y-1.5">
            <div className="flex items-center justify-between">
              <span className="text-xs font-bold text-slate-700 dark:text-slate-300 flex items-center gap-1.5">
                <span>Pratinjau Pesan WhatsApp</span>
                {isCustomEditing ? (
                  <span className="text-[10px] font-medium text-amber-600 dark:text-amber-400">(Sedang diedit)</span>
                ) : (
                  <span className="text-[10px] font-medium text-slate-400">({finalReportText.length} karakter)</span>
                )}
              </span>
              <button
                type="button"
                onClick={handleCopy}
                className="text-[11px] font-semibold text-blue-700 dark:text-blue-300 hover:text-blue-800 flex items-center gap-1 px-2 py-1 rounded-lg hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors"
              >
                {copied ? <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
                <span className={copied ? 'text-emerald-600 font-bold' : ''}>{copied ? 'Tersalin!' : 'Salin Teks'}</span>
              </button>
            </div>

            <div className="bg-[#EFEAE2] dark:bg-slate-950 p-3.5 rounded-2xl border border-slate-300/80 dark:border-slate-800">
              {isCustomEditing ? (
                <div className="space-y-2">
                  <textarea
                    value={editedText}
                    onChange={(e) => setEditedText(e.target.value)}
                    rows={10}
                    placeholder="Ketik atau sesuaikan pesan laporan di sini..."
                    className="w-full p-3 bg-white dark:bg-slate-900 rounded-xl shadow-xs border border-amber-300 dark:border-amber-700 font-mono text-[11px] text-slate-800 dark:text-slate-200 leading-relaxed focus:outline-hidden focus:ring-2 focus:ring-amber-500"
                  />
                  <div className="flex items-center justify-between text-[10px] text-slate-500 dark:text-slate-400 px-1">
                    <span>*tips: Gunakan tanda *tebal* dan _miring_ untuk format WhatsApp.</span>
                    <button
                      type="button"
                      onClick={() => setIsCustomEditing(false)}
                      className="text-amber-700 dark:text-amber-300 font-bold hover:underline"
                    >
                      Selesai Menyunting
                    </button>
                  </div>
                </div>
              ) : (
                <div className="bg-white dark:bg-slate-900 rounded-xl p-3 shadow-xs border border-blue-200/50 dark:border-blue-900/30 font-mono text-[11px] text-slate-800 dark:text-slate-200 whitespace-pre-wrap leading-relaxed max-h-56 overflow-y-auto">
                  {finalReportText}
                </div>
              )}
            </div>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="pt-3 border-t border-slate-100 dark:border-slate-800 space-y-2 shrink-0">
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-2">
            {/* Primary Action: Direct WhatsApp App */}
            <button
              type="button"
              onClick={handleSendWA}
              className="w-full inline-flex items-center justify-center gap-2 py-2.5 px-3 rounded-xl bg-gradient-to-r from-emerald-600 to-teal-600 hover:from-emerald-700 hover:to-teal-700 text-white font-extrabold text-xs shadow-soft-sm transition-all active:scale-98 cursor-pointer"
            >
              <Send className="w-4 h-4" />
              <span>Kirim ke No. WA Karu</span>
            </button>

            {/* General WhatsApp: Select from Contact List */}
            <button
              type="button"
              onClick={handleSendGeneralWA}
              className="w-full inline-flex items-center justify-center gap-2 py-2.5 px-3 rounded-xl bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 text-slate-800 dark:text-slate-200 font-bold text-xs border border-slate-200 dark:border-slate-700 transition-all active:scale-98 cursor-pointer"
              title="Buka WhatsApp dan pilih kontak Karu secara manual"
            >
              <ExternalLink className="w-4 h-4 text-emerald-600 dark:text-emerald-400" />
              <span>Pilih Kontak di WA</span>
            </button>

            {/* WhatsApp Web Browser Option */}
            <button
              type="button"
              onClick={handleSendDesktopWeb}
              className="w-full inline-flex items-center justify-center gap-2 py-2.5 px-3 rounded-xl bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 text-slate-800 dark:text-slate-200 font-bold text-xs border border-slate-200 dark:border-slate-700 transition-all active:scale-98 cursor-pointer"
              title="Buka WhatsApp Web di tab browser baru (Cocok untuk Laptop/PC)"
            >
              <Globe className="w-4 h-4 text-blue-600 dark:text-blue-400" />
              <span>Buka WA Web (PC)</span>
            </button>
          </div>

          <div className="flex items-center justify-between text-[11px] text-slate-500 dark:text-slate-400 px-1 pt-1">
            <span>Teks laporan otomatis disalin ke clipboard saat diklik.</span>
            <a
              href={manualUrl}
              target="_blank"
              rel="noopener noreferrer"
              onClick={onClose}
              className="text-emerald-600 dark:text-emerald-400 hover:underline inline-flex items-center gap-1 font-semibold"
            >
              <span>Buka link manual</span>
              <ExternalLink className="w-3 h-3" />
            </a>
          </div>
        </div>
      </div>
    </div>
  );
};
